# Generated by Django 3.1.4 on 2021-02-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_teachernewnotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachernewnotice',
            old_name='notice_id',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='teachernewnotice',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
