# Generated by Django 3.1.4 on 2021-02-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_auto_20210211_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=511)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('new', models.IntegerField(default=1)),
                ('isOpen', models.IntegerField(default=1)),
                ('receiverStu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverStu_id', to='ex.student')),
                ('receiverTea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverTea_id', to='ex.teacher')),
                ('senderStu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderStu_id', to='ex.student')),
                ('senderTea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderTea_id', to='ex.teacher')),
            ],
        ),
    ]
