# Generated by Django 3.1.4 on 2021-02-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_privateletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateletter',
            name='isOpen',
        ),
        migrations.CreateModel(
            name='ChatBoxIsOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOpen', models.IntegerField(default=1)),
                ('receiverStu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverStuIsOpen_id', to='ex.student')),
                ('receiverTea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverTeaIsOpen_id', to='ex.teacher')),
                ('senderStu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderStuIsOpen_id', to='ex.student')),
                ('senderTea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderTeaIsOpen_id', to='ex.teacher')),
            ],
        ),
    ]
