# Generated by Django 3.1.4 on 2021-02-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0006_auto_20210212_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=511)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('userStu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.student')),
                ('userTea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.teacher')),
            ],
        ),
    ]
