# Generated by Django 3.1.4 on 2021-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=31),
            preserve_default=False,
        ),
    ]
