# Generated by Django 3.1.4 on 2021-02-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0010_thumbsup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachernewnotice',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachernewnotice',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.student'),
        ),
    ]
