# Generated by Django 3.1.4 on 2021-02-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0011_auto_20210227_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachernewnotice',
            name='student',
        ),
        migrations.AddField(
            model_name='teachernewnotice',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.teacher'),
        ),
        migrations.CreateModel(
            name='StudentNewNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.IntegerField(default=1)),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.notice')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.student')),
            ],
        ),
    ]
