# Generated by Django 3.1.4 on 2021-03-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0013_experiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ex_name',
        ),
        migrations.AddField(
            model_name='report',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.experiment'),
        ),
    ]
