# Generated by Django 3.1.4 on 2021-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0014_auto_20210308_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21, null=True)),
                ('college', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
