# Generated by Django 3.1.4 on 2021-03-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0015_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='experimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exPurpose', models.CharField(max_length=512, null=True)),
                ('systemScore', models.IntegerField(default=-1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.experiment')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.group')),
            ],
        ),
    ]
