# Generated by Django 3.1.4 on 2021-04-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0019_tlcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.group')),
                ('tlComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.tlcomment')),
            ],
        ),
        migrations.CreateModel(
            name='TLGroupVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.group')),
                ('tlVote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.tlvote')),
            ],
        ),
    ]
