# Generated by Django 3.1.4 on 2021-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0020_tlgroupvote_tlvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdata',
            name='exExperience',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='exResult',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='exSteps',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
