# Generated by Django 3.1.4 on 2021-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0023_experimentdata_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='introduction',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='introductionUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
